(use-package lsp-mode
  :init
  (setq lsp-keymap-prefix "C-c l")
  (setq lsp-pylsp-plugins-pycodestyle-enabled nil)
  (setq lsp-pylsp-plugins-flake8-enabled t)
  (setq lsp-pylsp-plugins-pycodestyle-max-line-length 120)
  (setq lsp-pylsp-plugins-flake8-max-line-length 120)
  (setq lsp-pylsp-plugins-yapf-enabled t)
  (setq lsp-pyls-plugins-pycodestyle-enabled t)
  (setq lsp-pyls-plugins-flake8-enabled t)
  (setq lsp-pyls-plugins-pycodestyle-max-line-length 120)
  :hook
  (scala-mode . lsp)
  (python-mode . lsp)
  :commands lsp
  :bind
  (:map lsp-mode-map
        ("C-c j" . lsp-find-definition)
        ([M-down-mouse-1] . mouse-set-point)
        ([M-mouse-1] . lsp-find-definition)
        ("<f4>" . lsp-rename)))

(use-package lsp-ui)
