(use-package modus-themes)

(defun my/load-light-theme ()
  (modus-themes-load-operandi))

(defun my/load-dark-theme ()
  (modus-themes-load-vivendi))

(defun my/apply-theme (appearance)
  (mapc #'disable-theme custom-enabled-themes)
  (pcase appearance
    ('light (my/load-light-theme))
    ('dark (my/load-dark-theme))))

(add-hook 'ns-system-appearance-change-functions #'my/apply-theme)

(custom-set-faces
 '(mode-line ((t (:background "dark blue" :foreground "white")))))
